### ISSUE TITLE
Supress reporting on 'required, if applicable' attributes.  Fix gts_ingest notification messaging.  

### ISSUE THREAD

**Issue by mwengren** [ioos/compliance-checker#757]
Looking at some output from some example datasets we've listed in #723, I ran a test on PacIOOS' [AWS-HIMB](https://pae-paha.pacioos.hawaii.edu/erddap/info/AWS-HIMB/index.html) dataset.  

Output is available here for reference: [HTML](https://gist.github.com/mwengren/82496d8114bab0776ae34ef70510b2a1), [JSON](https://gist.github.com/mwengren/df78535eb260133df8ac6b92e1fb72d2).

Both the `gts_ingest` (variable) check and `wmo_platform_code` (global) checks should probably not produce notification messages if not present.  Reason is that not all datasets will be destined for GTS.  This is why the phrase 'required, if applicable' is used: each is not explicitly required for a dataset to comply with the Profile.  

We probably want the test instead to check for presence of a global `wmo_platform_code` attribute, and if present, confirm it meets format requirements (5 alphanumeric or 7 numeric digits).

Same for any variables with `gts_ingest` attribute (it should either be `true|false`).  

If neither is present, no notification message.

As these both are now, it results in cluttered output messages that aren't really relevant for many datasets.  

Also, second issue on the `gts_ingest` variable test: the notification message contains text from the [Requirements for GTS Ingest](https://ioos.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html#requirements-for-ioos-dataset-gts-ingest) section; these requirements shouldn't be included here.  The `gts_ingest` attribute represents a subset of these larger requirements, so it doesn't make sense to report them on this specific test.

If it's possible to write a separate test to check that a dataset includes any variables that meet the GTS ingest attribution requirements, that would be cool and worth adding.  Separate issue to come.

**Comment by daltonkell** [comment]
The `wmo_platform_code` piece of this issue is addressed by #766

**Comment by mwengren** [comment]
Testing this dataset as of 4.3.3rc2:

http://erddap.sensors.ioos.us/erddap/tabledap/ssbn7-sun2wave-sun2w-sunset-n

Shows that the `gts_ingest` output is still appearing in results.  

For both **'required, if applicable'** global `gts_ingest` and `wmo_platform_code` attributes, as mentioned above, we should skip reporting on them if they are omitted in the dataset.  

Only if each attribute is present, should syntax checks be done and output messages generated.

**Comment by daltonkell** [comment]
@mwengren it seems that the text output (default) doesn't output this message, but the HTML output and JSON output do... strange. I think I'll open a new issue for this.

**Comment by mwengren** [comment]
Resolved by #787, closing.
